[package]
name = "capi-host"
edition = "2021"

[dependencies]
anyhow = "*"
ron = "*"

[dependencies.capi-game-engine]
path = "../game-engine"

[dependencies.capi-ffi]
path = "../ffi"

[dependencies.capi-protocol]
path = "../protocol"

[dependencies.capi-runtime]
path = "../runtime"
