[package]
name = "cp1"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "*"
futures = "*"

[dependencies.crossterm]
version = "*"
features = ["event-stream"]

[dependencies.tokio]
version = "*"
features = ["full"]
