[package]
name = "capi-watch"
edition = "2021"

[dependencies]
anyhow = "*"
tracing = "*"

[dependencies.notify]
version = "*"
default-features = false

[dependencies.tokio]
version = "*"
features = ["process", "rt", "sync", "time"]
