[package]
name = "cp2"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "*"
futures = "*"
thiserror = "*"

[dependencies.crossterm]
version = "*"
features = ["event-stream"]

[dependencies.tokio]
version = "*"
features = ["full"]
